### ISSUE TITLE
Referencing wrong docker image version

### ISSUE THREAD

**Issue by mbuelowdev** [johnluicn/devcontainer-templates#3]
Hello there,

you are referencing "5.2.0" as imageVariant version in [src/esp-idf/devcontainer-template.json](https://github.com/johnluicn/devcontainer-templates/blob/main/src/esp-idf/devcontainer-template.json) which apparently doesn't exist anymore. Because of this an error is thrown at the setup stage.

```
[37735 ms] Start: Run: docker pull espressif/idf:5.2.0
Error response from daemon: manifest for espressif/idf:5.2.0 not found: manifest unknown: manifest unknown
[39045 ms] []
[39045 ms] Error: No such image: espressif/idf:5.2.0

[38812 ms] Error: Command failed: docker inspect --type image espressif/idf:5.2.0
[38812 ms]     at atA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:464:1260)
[38812 ms]     at yH (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:464:1002)
[38812 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[38812 ms]     at async StA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:481:3660)
[38813 ms]     at async ZC (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:481:4775)
[38813 ms]     at async trA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:614:11269)
[38813 ms]     at async erA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.348.0/dist/spec-node/devContainersSpecCLI.js:614:11010)
[38816 ms] Exit code 1
```

However "v5.2" exists. https://hub.docker.com/r/espressif/idf/tags?page=1&name=5.2

A quick change from "5.2.0" to "v5.2" or "release-v5.2" could maybe fix this.

**Comment by sanchuanhehe** [comment]
yes,i have the same problem
